name: HelperBot
version: 2.2
main: me.Delocaz.HelperBot.HelperBot
author: Delocaz
commands:
    help:
        usage: /<command> <page>
        aliases: [helpme, plzhelp, icanhazhelp, halp]
    addhelp:
        usage: /<command> <page> <content>
    delhelp:
        usage: /<command> <page>